depot(hochwald_ost,148).
depot(lichtendorf_sued,70).
depot(muensterland_ost,275).
depot(remscheid_ost,381).
restaurant(aarbachkate_sued,36).
restaurant(buddikate_ost,25).
restaurant(buddikate_west,25).
restaurant(dammer_berge_ost,194).
restaurant(dammer_berge_west,194).
restaurant(ehrenberg_west,368).
restaurant(eichengrund_west,296).
restaurant(eifel_ost,93).
restaurant(eifel_west,93).
restaurant(grundbergsee_nord,86).
restaurant(grundbergsee_sued,86).
restaurant(hamburg_stillhorn_ost,155).
restaurant(hamburg_stillhorn_west,155).
restaurant(hochwald_ost,148).
restaurant(hochwald_west,148).
restaurant(hollenstedt,36).
restaurant(im_mersch_ost,296).
restaurant(kucksiepen,367).
restaurant(lennhof_west,61).
restaurant(lichtendorf_nord,70).
restaurant(lichtendorf_sued,70).
restaurant(muensterland_ost,275).
restaurant(muensterland_west,276).
restaurant(neustaedter_bucht_ost,81).
restaurant(neustaedter_bucht_west,81).
restaurant(ostetal_nord,51).
restaurant(ostetal_sued,51).
restaurant(oyten_sued,97).
restaurant(remscheid_ost,381).
restaurant(remscheid_west,381).
restaurant(tecklenburger_land_ost,234).
restaurant(tecklenburger_land_west,234).
restaurant(trave,43).
restaurant(ville_ost,431).
restaurant(ville_west,431).
restaurant(wildeshausen_nord,142).
restaurant(wildeshausen_sued,144).
