depot(bayerischer_wald_nord,540).
depot(wuerzburg_sued,289).
depot(sessenhausen_west,70).
restaurant(aurach_nord,375).
restaurant(aurach_sued,375).
restaurant(bad_camberg_ost,123).
restaurant(bad_camberg_west,123).
restaurant(bayerischer_wald_nord,540).
restaurant(bayerischer_wald_sued,540).
restaurant(donautal_ost,605).
restaurant(donautal_west,605).
restaurant(elten_west,0).
restaurant(epgert_ost,54).
restaurant(fernthal_west,50).
restaurant(haidt_nord,312).
restaurant(haidt_sued,312).
restaurant(heiligenroth_west,89).
restaurant(hoesel_ost,301).
restaurant(huenxe_ost,52).
restaurant(huenxe_west,52).
restaurant(jura_ost,440).
restaurant(jura_west,439).
restaurant(koenigsforst_ost,7).
restaurant(koenigsforst_west,7).
restaurant(landsberg_an_der_warthe,72).
restaurant(limburg_ost,107).
restaurant(limburg_west,107).
restaurant(medenbach_ost,143).
restaurant(medenbach_west,143).
restaurant(montabaur_ost,86).
restaurant(nentershausen_ost,95).
restaurant(ohligser_heide_ost,520).
restaurant(ohligser_heide_west,112).
restaurant(sessenhausen_west,70).
restaurant(siegburg_ost,19).
restaurant(siegburg_west,19).
restaurant(spessart_nord,237).
restaurant(spessart_sued,238).
restaurant(steigerwald_nord,353).
restaurant(steigerwald_sued,350).
restaurant(urbacher_wald_ost,63).
restaurant(weiskirchen_nord,193).
restaurant(weiskirchen_sued,193).
restaurant(wuerzburg_nord,289).
restaurant(wuerzburg_sued,289).
