depot(hannover_wuelferode_west,155).
depot(lonetal_west,818).
depot(huettener_berge_west,55).
restaurant(aalbek_west,93).
restaurant(allertal_ost,106).
restaurant(allertal_west,106).
restaurant(allgaeuer_tor_ost,910).
restaurant(allgaeuer_tor_west,910).
restaurant(brokenlande_ost,102).
restaurant(brunautal_ost,51).
restaurant(brunautal_west,51).
restaurant(ellund_west,0).
restaurant(ellwanger_berge_ost,769).
restaurant(ellwanger_berge_west,769).
restaurant(goettingen_ost,271).
restaurant(goettingen_west,272).
restaurant(grossenmoor_ost,543).
restaurant(grossenmoor_west,542).
restaurant(hannover_wuelferode_ost,160).
restaurant(hannover_wuelferode_west,155).
restaurant(harburger_berge_ost,174).
restaurant(harburger_berge_west,173).
restaurant(hasselberg_ost,340).
restaurant(hasselberg_west,340).
restaurant(hasselhoehe_west,22).
restaurant(hildesheimer_boerde_ost,157).
restaurant(hildesheimer_boerde_west,157).
restaurant(holmmoor_ost,136).
restaurant(holmmoor_west,136).
restaurant(huettener_berge_ost,55).
restaurant(huettener_berge_west,55).
restaurant(illertal_ost,874).
restaurant(illertal_west,874).
restaurant(kassel_ost,314).
restaurant(kassel_west,312).
restaurant(kirchheim_ost,524).
restaurant(lonetal_ost,818).
restaurant(lonetal_west,818).
restaurant(ohrenbach_ost,705).
restaurant(ohrenbach_west,705).
restaurant(rhoen_ost,603).
restaurant(rhoen_west,603).
restaurant(riedener_wald_ost,648).
restaurant(riedener_wald_west,647).
restaurant(harz_ost,223).
restaurant(harz_west,232).
restaurant(seevetal_ost,21).
restaurant(uttrichshausen_ost,579).
restaurant(uttrichshausen_west,579).
restaurant(vorm_wietzenbruch_west,69).
