restaurant(flaeming_ost,23).
restaurant(flaeming_west,23).
restaurant(frankenwald_ost,244).
restaurant(frankenwald_west,245).
restaurant(fraenkische_schweiz_pegnitz_ost,332).
restaurant(fraenkische_schweiz_pegnitz_west,332).
restaurant(fuerholzen_ost,510).
restaurant(greding_ost,423).
restaurant(greding_west,421).
restaurant(hermsdorfer_kreuz_ost,187).
restaurant(hermsdorfer_kreuz_west,187).
restaurant(hirschberg_ost,242).
restaurant(in_der_holledau_west,485).
restaurant(koeckern_ost,96).
restaurant(koeckern_west,96).
restaurant(koeschinger_forst_ost,450).
restaurant(nuernberg_feucht_ost,385).
restaurant(nuernberg_feucht_west,385).
restaurant(osterfeld_ost,158).
restaurant(osterfeld_west,158).
restaurant(koeschinger_forst__west,450).
depot(flaeming_ost,23).
depot(frankenwald_ost,244).
depot(fraenkische_schweiz_pegnitz_ost,332).
depot(in_der_holledau_west,485).
depot(koeckern_ost,96).
depot(nuernberg_feucht_west,385).
depot(osterfeld_ost,158).
depot(koeschinger_forst__west,450).
