# If GECODE_ROOT was defined in the environment, use it.
if (NOT GECODE_ROOT AND NOT $ENV{GECODE_ROOT} STREQUAL "")
	set(GECODE_ROOT $ENV{GECODE_ROOT})
endif(NOT GECODE_ROOT AND NOT $ENV{GECODE_ROOT} STREQUAL "")

IF(GECODE_USE_STATIC_LIBS OR USE_STATIC_LIBS)
	SET(CMAKE_FIND_LIBRARY_SUFFIXES .lib .a)
ENDIF()
FOREACH(LIBRARY gecodesearch gecodesupport gecodeminimodel gecodeint gecodekernel gecodeset pthread dl)
	FIND_LIBRARY(GECODE_LIBRARY_${LIBRARY} ${LIBRARY} PATH "${GECODE_ROOT}/lib")
	IF(NOT GECODE_LIBRARY_${LIBRARY})
		SET(ERROR TRUE)
	ELSE(NOT GECODE_LIBRARY_${LIBRARY})
		SET(GECODE_LIBRARIES ${GECODE_LIBRARIES} ${GECODE_LIBRARY_${LIBRARY}})
	ENDIF(NOT GECODE_LIBRARY_${LIBRARY})
ENDFOREACH(LIBRARY)

FIND_PATH(GECODE_INCLUDE "gecode/search.hh" PATH "${GECODE_ROOT}/include")
IF(NOT GECODE_INCLUDE)
	SET(ERROR TRUE)
ENDIF(NOT GECODE_INCLUDE)

IF(NOT ERROR)
	SET(GECODE_FOUND TRUE)
ENDIF(NOT ERROR)

MESSAGE(STATUS ${GECODE_LIBRARIES})

IF (GECODE_FOUND)
   IF (NOT GECODE_FIND_QUIETLY)
      MESSAGE(STATUS "Found Gecode: ${GECODE_LIBRARY_gecodesearch}")
   ENDIF (NOT GECODE_FIND_QUIETLY)
ELSE (GECODE_FOUND)
   IF (GECODE_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Gecode")
   ENDIF (GECODE_FIND_REQUIRED)
ENDIF (GECODE_FOUND)


