if(NOT $ENV{CROSS_COMPILER} STREQUAL "")
	SET(CROSS_COMPILER $ENV{CROSS_COMPILER})
endif()
if(NOT CROSS_COMPILER)
	SET(CROSS_COMPILER "i586-mingw32msvc")
endif()

SET(CROSS_COMPILER ${CROSS_COMPILER} CACHE STRING "the cross compiler to use")

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_C_COMPILER "${CROSS_COMPILER}-gcc")
set(CMAKE_CXX_COMPILER "${CROSS_COMPILER}-g++")

SET(CMAKE_FIND_ROOT_PATH /usr/"${CROSS_COMPILER}" $ENV{HOME}/local/mingw32)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
